config/routes.rb
Rails.application.routes.draw do
  resources :charges, only: [:new, :create] do
    member do
      post :downgrade
    end
  end

  resources :wikis

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  resource :users, only: [:show]

  devise_for :users
  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis, dependent: :destroy
  has_many :collaborators, dependent: :destroy
  has_many :shared_wikis, through: :collaborators, source: :wiki

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save { self.role ||= :standard }

  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators

  default_scope { order('created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
    
    stripe_id(customer)

    # Where the magic happens
    charge = Stripe::Charge.create(
      # Stripe customer id not blocipedia id.
      customer: customer.id,
      amount: 15_00,
      description: "Blocipedia Premium Membership- #{current_user.email}",
      currency: 'usd'
    )

    update_role

    flash[:notice] = "Thanks for all the money, #{current_user.email}!
    Feel free to pay me again."

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to root_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Premium Membership - #{current_user.email}",
      amount: 15_00
    }
  end

  def stripe_id(customer)
    current_user.stripe_id = customer.id
    current_user
  end

  def update_role
    current_user.premium!

    if @current_user.save
      flash[:notice] = "You're account has been upgraded."
      redirect_to wikis_path
    else
      flash[:alert] = "Something went wrong. Please try again."
    end
  end

  def downgrade
    wiki = Wiki.where(user_id: current_user.id)
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    customer.delete
    wiki.update_all(private: nil)
    current_user.standard!

    if current_user.save
      flash[:notice] = "You have successfully downgraded your account."
      redirect_to wikis_path
    else
      flash.now[:notice] = "Something went wrong. Please try again."
      redirect_to edit_user_registration_path
    end
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def new
    @collaborator = Collaborator.new
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])

    if @collaborator.save
      flash[:notice] = "Collaborator was added to this wiki."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "Collaborator was not added. Please try again."
      render :show
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator was removed from this wiki."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "Collaborator was not removed. Please try again."
      render :show
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
include ApplicationHelper

class WikisController < ApplicationController
  before_action :authenticate_user!

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])

    if @wiki.private && current_user.standard?
      flash[:alert] = "You must be a premium member to view this Wiki."
      redirect_to wikis_path
    end
  end

  def new
    @wiki = Wiki.new
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user_id = current_user.id

    if @wiki.save
      flash[:notice] = "Wiki was created."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki."
      render :edit
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "Wiki was deleted."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was a problem deleting the wiki. Please try again."
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true,
      tables: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class="col-lg-4 text-center">
  <h2>Upgrade to Premium Account</h2>
  <h3>$15.00</h3>

  <p>You get unlimited public/private wikis</p>

  <%= form_tag charges_path do %>
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid" style="padding: 0;">
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>

        <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        </div>
      </ul>
    </div>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="container-fluid blocipedia-jumbo">
  <div class="title" align="center">
    <h1>Blocipedia</h1>
  </div>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-4 text-center">
        <div class="well">
          <h3>Standard Account</h3>
          <h3>FREE<h3>
          <h5>Allows For:</h5>
          <p>Creating Public Wikis</p>
          <p>Editing Public Wikis</p>
          <p>Reading Public Wikis</p>
        </div>
    </div>

    <div class="col-md-4 text-center">
        <div class="well">
          <h3>Premium Account</h3>
          <h3>$15.00<h3>
          <h5>Allows For:</h5>
          <p>Creating Public/Private Wikis</p>
          <p>Editing Public/Private Wikis</p>
          <p>Reading Public/Private Wikis</p>
        </div>
    </div>
  </div>
  <div class="row text-center">
  <% if !user_signed_in? %>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-lg btn-success' %>
  <% end %>
  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  <div>
    <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private wiki
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/_wiki.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to wiki.title, wiki_path(wiki) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.name %> <br>
    </small>
  </div>
</div>

app/views/wikis/edit.html.erb
<div align="center">
<h1>Edit Wiki</h1>
</div>

<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>

      <h3>Add Collaborators</h3>

      <% if @wiki.user_id == current_user.id || current_user.admin? %>
        <div class="form-group">
        <% User.all.each do |user| %>

          <% if @wiki.users.include? user %>
          <div>
            <%= link_to "Remove", wiki_collaborator_path(@wiki, @wiki.collaborators.find_by_user_id(user.id).id), method: :delete, class: 'btn btn-danger' %>
            <strong><%= user.email %></strong>
          </div>
          <% else %>
          <div>
            <%= link_to "Add", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-info' %>
            <strong><%= user.email %></strong>
          </div>
          <% end %>
        <% end %>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="container">
  <h1>Wikis</h1>

  <% @wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <% if wiki.private && current_user.standard? %>
            <p><%= link_to wiki.title, wiki %> - <small>Private</small></p>
          <% else %>
            <p><%= link_to wiki.title, wiki %></p>
          <% end %>
        </h4>
      </div>
    </div>
  <% end %>

  <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
</div>

app/views/wikis/new.html.erb
<div class="container">
  <h1>New Wiki</h1>

  <div class="row">
    <div class="col-md-8">
    <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="container">
<h1><%= @wiki.title %></h1>

  <div class="row">
    <div class="col-md-8">
      <p><%= markdown(@wiki.body) %></p>  </div>
    <div class="col-md-4">
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger',  data: {confirm: 'Are you sure you want to delete this post?'} %>
    </div>
  </div>
</div>